export const PHONE_VERIFICATION = {
  CODE_VALIDITY_SECONDS: 5 * 60,
  TIMER_DURATION_SECONDS: 15 * 60,
  MIN_PHONE_LENGTH: 8,
  CODE_LENGTH: 6,
  CODE_EXPIRY_WARNING_SECONDS: 60,
  RECAPTCHA_CONTAINER_ID: "phone-modal-recaptcha",
} as const;
